### ISSUE TITLE
Add to awesome-cakephp

### ISSUE THREAD

**Issue by dereuromark** [drmonkeyninja/cakephp-social-share#1]
Feel free to add it to https://github.com/FriendsOfCake/awesome-cakephp list.

Saw your commit https://github.com/FriendsOfCake/awesome-cakephp/commit/ee6e9df8eb1f45c4668ece6dd7a638ef8eb36fe5 the other day :)

**Comment by drmonkeyninja** [comment]
Just created a pull request for this.

Always happy to help curate the list. It's a useful resource.
