### ISSUE TITLE
Regarding version? Is that work for cakephp 3.2?

### ISSUE THREAD

**Issue by mandeepkumar0856** [drmonkeyninja/cakephp-social-share#13]
Hello dear Can you tell me how i use it and how i run it on my console and what changes are made by me in my project.
When i install it on my project it does not work for me. i run the following command in my console 
step 1.composer require drmonkeyninja/cakephp-social-share:3.0.*
step 2. in config /bootstrap .php Plugin::load('SocialShare');
i use this command instaed of Plugin::load('Migration');
step3.in my controller i use this line
public $helpers = ['SocialShare.SocialShare'];
step 4 in my template in .ctp file  echo $this->SocialShare->link(
    'facebook',
    __('Share on Facebook')
);
So please tell me may i need to another changes in my controller my mean is that in  (vendor/src/controller)  i don't use these controller in my controller.so please tell me why it not work for me.Please help me i am new in cakephp ?and i want to login through social site and made all functionality like how we change password,forget password,like function,comments function and also captca function in my login pannel.so please help me dears.

**Comment by drmonkeyninja** [comment]
I think you've possibly misunderstood what this plugin does. The code you've described should output a link that when clicked allows the user to share the current page on Facebook.

It does not provide authentication, commenting or captcha. You will need to look elsewhere for this sort of functionality.
