### ISSUE TITLE
Whatsapp 

### ISSUE THREAD

**Issue by beinbm** [drmonkeyninja/cakephp-social-share#3]
Hi,

can you add whatsapp? Should be very easy:
https://github.com/heiseonline/shariff/blob/master/src/js/services/whatsapp.js

Thanks,
Marco

**Comment by drmonkeyninja** [comment]
Will look into adding this for the next release.

**Comment by amontrope** [comment]
This is quite late to say but this WhatsApp link would only show on mobile or if WhatsApp is installed on your system, I think it is better to use the WhatsApp API links which will open the protocol and still show for desktop browsers. The syntax for that is https://api.whatsapp.com/send?phone={number}&text={message} where {number} is the whatsapp number in international format with area code and only numeric characters and {message} is the URL encoded message . Either can be null.

**Comment by drmonkeyninja** [comment]
@amontrope thanks for mentioning this. I don't personally use WhatsApp, do you know if with that API call if the `phone` value is emitted does it give the user the opportunity to choose a number to send the message too? If it does I'd be happy to add this, possibly as a separate option. This repo itself doesn't handle the url generation anymore, it uses [social-share-url](https://github.com/drmonkeyninja/social-share-url) but it can be easily implemented there.

**Comment by amontrope** [comment]
Yes. If you leave the phone value omitted it will bring up the option to choose which contacts to send the message to just like how it's done currently.
