### ISSUE TITLE
CakePHP3.x

### ISSUE THREAD

**Issue by dereuromark** [drmonkeyninja/cakephp-social-share#6]
See https://github.com/drmonkeyninja/cakephp-social-share/compare/drmonkeyninja:master...dereuromark:3.0
incl. travis passing ( https://travis-ci.org/dereuromark/cakephp-social-share/builds )

Also added:
- services() to get a list of the services, good when you want to iterate over them

Live preview (cake3): http://sandbox3.dereuromark.de/sandbox/social-share

**Comment by drmonkeyninja** [comment]
Hi thanks for this @dereuromark. The new services() function is a really good idea.

Is there a reason why you've committed phpunit.phar to the repository? I'm guessing this is to do with travis (I only started looking into this the other day) but would have thought this doesn't belong in the repository and should be installed via Composer.

**Comment by dereuromark** [comment]
My mistake :)

**Comment by drmonkeyninja** [comment]
Thanks @dereuromark this has now been merged into the repository.

**Comment by dereuromark** [comment]
Once you got the travis setup all done, please feel free to add it to the awesome list for 3.x branch (master).
