### ISSUE TITLE
installer name not needed

### ISSUE THREAD

**Issue by dereuromark** [drmonkeyninja/cakephp-social-share#9]
I think you can drop this for 3.x:
https://github.com/drmonkeyninja/cakephp-social-share/blob/master/composer.json#L32-L33

**Comment by dereuromark** [comment]
Also, the mix of spaces and tabs could be the reason that I cannot install the current 3.x dev-master branch ( https://github.com/drmonkeyninja/cakephp-social-share/blob/master/composer.json )

```
  [RuntimeException]
  Unable to get primary namespace for package drmonkeyninja/cakephp-social-sh
  are.
  Ensure you have added proper 'autoload' section to your plugin's config as
  stated in README on https://github.com/cakephp/plugin-installer
```

**Comment by drmonkeyninja** [comment]
I've fixed the tabbing so hopefully this will have fixed this for you. I've also removed the installer name. Not quite sure why this was failing for you before as it was passing the travis tests.

**Comment by dereuromark** [comment]
Cool :)
